-- lua/koda/groups/treesitter.lua
local M = {}

local utils = require("koda.utils")

--- Get Treesitter highlight groups
---@param c koda.Palette The color palette
---@param opts koda.Config User configuration
---return table<string, table> # highlight groups table
function M.get(c, opts)
    -- stylua: ignore
    return {
      ["@variable"]                    = { link = "Identifier" },
      ["@variable.builtin"]            = { fg = c.const  }, -- e.g. this, self
      ["@variable.parameter"]          = { link = "Identifier" },
      ["@variable.parameter.builtin"]  = { link = "Identifier" },
      ["@variable.member"]             = { link = "Identifier" },
      ["@constant"]                    = { link = "Constant" },
      ["@constant.macro"]              = { link = "Constant" },
      ["@constant.builtin"]            = { link = "Constant" },
      ["@module"]                      = { link = "Structure" },
      ["@module.builtin"]              = { link = "Special" },
      ["@label"]                       = { link = "Structure" },
      ["@string"]                      = { link = "String" },
      ["@string.documentation"]        = { link = "Comment" },
      ["@string.regexp"]               = { link = "String" },
      ["@string.escape"]               = { link = "Special" },
      ["@string.special"]              = { link = "Special" },
      ["@string.special.symbol"]       = { link = "Special" },
      ["@string.special.path"]         = { link = "Special" },
      ["@string.special.url"]          = { link = "Underlined" },
      ["@character"]                   = { link = "Character" },
      ["@character.special"]           = { link = "Special" },
      ["@boolean"]                     = { link = "Boolean" },
      ["@number"]                      = { link = "Number" },
      ["@number.float"]                = { link = "Number" },
      ["@type"]                        = { link = "Type" },
      ["@type.builtin"]                = { link = "Type" },
      ["@type.definition"]             = { link = "Type" },
      ["@attribute"]                   = { link = "Keyword" },
      -- ["@attribute.builtin"]        = { link = "Keyword" },
      ["@property"]                    = { link = "Identifier" },
      ["@function"]                    = { link = "Function" },
      ["@function.builtin"]            = { link = "Function" },
      ["@function.call"]               = { link = "Function" },
      ["@function.macro"]              = { link = "Macro" },
      ["@function.method"]             = { link = "Function" },
      ["@function.method.call"]        = { link = "Function" },
      ["@constructor"]                 = { link = "Identifier" },
      ["@operator"]                    = { link = "Operator" },
      ["@keyword"]                     = { link = "Keyword" },
      -- ["@keyword.coroutine"]        = { link = "Keyword" },
      ["@keyword.function"]            = { link = "Keyword" },
      ["@keyword.operator"]            = { link = "Operator" },
      ["@keyword.import"]              = { link = "Include" },
      ["@keyword.type"]                = { link = "Keyword" },
      ["@keyword.modifier"]            = { link = "Keyword" },
      ["@keyword.repeat"]              = { link = "Repeat" },
      ["@keyword.return"]              = { fg = c.emphasis },
      ["@keyword.debug"]               = { link = "Keyword" },
      ["@keyword.exception"]           = { link = "Exception" },
      ["@keyword.conditional"]         = { link = "Conditional" },
      ["@keyword.conditional.ternary"] = { link = "Conditional" },
      ["@keyword.directive"]           = { link = "Keyword" },
      ["@keyword.directive.define"]    = { link = "Keyword" },
      ["@punctuation"]                 = { link = "Keyword" },
      ["@punctuation.delimiter"]       = { link = "Identifier" },
      ["@punctuation.bracket"]         = { link = "Delimiter" },
      ["@punctuation.special"]         = { link = "Delimiter" },
      ["@comment"]                     = { link = "Comment" },
      ["@comment.documentation"]       = { link = "Comment" },
      ["@comment.error"]               = { fg = c.danger },
      ["@comment.warning"]             = { fg = c.warning },
      ["@comment.todo"]                = { fg = c.info },
      ["@comment.note"]                = { fg = c.emphasis },
      ["@markup.strong"]               = { bold = true },
      ["@markup.italic"]               = { italic = true },
      ["@markup.strikethrough"]        = { fg = c.danger, strikethrough = true },
      ["@markup.underline"]            = { underline = true },
      ["@markup.heading"]              = { fg = c.info },
      ["@markup.heading.gitcommit"]    = { fg = c.fg },
      ["@markup.heading.1.markdown"]   = { fg = c.info, bg = utils.blend(c.info, c.bg, 0.1)},
      ["@markup.heading.2.markdown"]   = { fg = c.const, bg = utils.blend(c.const, c.bg, 0.1)},
      ["@markup.heading.3.markdown"]   = { fg = c.success, bg = utils.blend(c.success, c.bg, 0.1)},
      ["@markup.heading.4.markdown"]   = { fg = c.highlight, bg = utils.blend(c.highlight, c.bg, 0.1)},
      ["@markup.heading.5.markdown"]   = { fg = c.danger, bg = utils.blend(c.danger, c.bg, 0.1)},
      ["@markup.heading.6.markdown"]   = { fg = c.keyword, bg = utils.blend(c.keyword, c.bg, 0.1)},
      ["@markup.quote"]                = { link = "Comment" },
      ["@markup.math"]                 = { link = "Special" },
      ["@markup.link"]                 = { fg = c.info },
      ["@markup.link.label"]           = { fg = c.info },
      ["@markup.link.url"]             = { fg = c.info, underline = true },
      ["@markup.raw"]                  = { fg = c.const },
      ["@markup.raw.block"]            = { fg = c.const },
      ["@markup.list"]                 = { fg = c.emphasis },
      ["@markup.list.checked"]         = { fg = c.success },
      ["@markup.list.unchecked"]       = { fg = c.danger },
      ["@diff.plus"]                   = { link = "DiffAdd" },
      ["@diff.minus"]                  = { link = "DiffDelete" },
      ["@diff.delta"]                  = { link = "DiffChange" },
      ["@tag"]                         = { link = "Keyword" },
      -- ["@tag.builtin"]                         = { link = "Keyword" },
      ["@tag.delimiter"]               = { link = "Keyword" },
      ["@tag.attribute"]               = { link = "Keyword" },
    }
end

return M
